### ISSUE TITLE
How to get the English Gigaword dataset?

### ISSUE THREAD

**Issue by lan2720** [eecrazy/ConstructingNEEG_IJCAI_2018#1]
Hi, I don't know whether I need Gigaword Corpus or not if I want to run your code? If yes, where can I find this dataset? Thank you.

**Comment by lan2720** [comment]
That is, how to run this project? Could you write some README for clarification?

**Comment by eecrazy** [comment]
You need to download the data I used from google-drive in my paper, from the url given in README. Besides, you need Python3.5 or 3.6, PyTorch 0.3.0, and Nvidia GPU, perhaps Titan XP or Tesla P100. You can run python3 evaluate.py to get the results reported in my paper, and run python3 event_chain.py to train a PairLSTM model, and run python3 main_with_args.py to train a SGNN model. 

I have writen some annotations in my code, please read them and run! 

You don't need to download the Gigaword corpus, I have provided all the data you need to run the code.

**Comment by lan2720** [comment]
@eecrazy Great, it's quite clear now. Thank you.
