### ISSUE TITLE
Accuracy is low，do you have any good idea to raise this accuracy?

### ISSUE THREAD

**Issue by Himan000** [eecrazy/ConstructingNEEG_IJCAI_2018#3]
I tried your code and the best Acc: 52.3, which is too low for production. Do you have any good idea to raise this accuracy?

**Comment by eecrazy** [comment]
This task is based on unsupervised extracted narrative event chains, which is full of noise. This is a tradeoff between research and production. The data used in our paper maybe not good for production environment.

So what is your production environment？I think you should use clean and real data. And you can modify our algorithm to make it feasible to your production environment.

**Comment by Himan000** [comment]
Thanks for your reply. I just saw your reply. My environment are same tax law events. And thanks for your advice. I will modify some code accordingly.
