### ISSUE TITLE
麻烦能解释一下数据集中数据标签的含义吗？

### ISSUE THREAD

**Issue by yuppx** [eecrazy/ConstructingNEEG_IJCAI_2018#5]
(lp1
(lp2
(lp3
(S'struck'
S'strike'
S'subj'
p4
S'tiger'
S'sport'
Ntp5
a(S'is'
S'be'
g4
S'tiger'
S'youngest'
Ntp6
a(S'named'
S'name'
S'obj'
p7
S'si'
S'tiger'
Ntp8
a(S'follows'
S'follow'
g7
S'fascination'
S'tiger'
Ntp9
a(S'hold'
S'hold'
g4
S'tiger'
S'everyone'
Ntp10
a(S'sauntered'
S'saunter'
g4
S'tiger'
NS'pressure'
tp11
a(S'allowed'
S'allow'
g4
S'tiger'
S'tiger'
Ntp12
a(S'smile'
S'smile'
g4
S'tiger'
NNtp13
aa(lp14
(S'heated'
S'heat'
g7
S'open'
S'tiger'
S'indian'
tp15
a(S'sell'
S'sell'
g7
S'district'
S'tiger'
Ntp16
a(S'turns'
S'turn'
S'prep_on'
S'plot'
NS'tiger'
tp17
a(S'discussed'
S'discuss'
g7
NS'tiger'
Ntp18

**Comment by eecrazy** [comment]
这个数据的格式是pickle，请用python的pickle模块读取，就可以得到结构化的数据集了。
