### ISSUE TITLE
请问ReadMe中说的Gigaword corpus是不是没有了呀需要自己下载

### ISSUE THREAD

**Issue by PearLion** [eecrazy/ConstructingNEEG_IJCAI_2018#7]
您好，刚接触这个，是不是需要自己下载数据然后自行处理后再用您的模型吗？
谢谢！

**Comment by jianzhengming** [comment]
The similar problem happens to me. I don't know how to get the gigawords corpus.

**Comment by PearLion** [comment]
> The similar problem happens to me. I don't know how to get the gigawords corpus.

https://drive.google.com/open?id=1WFBDL_zfNC1sSuz0dmaMux3w-OB_hUui
