### ISSUE TITLE
Some questions about the gnn_with_args.py

### ISSUE THREAD

**Issue by jianzhengming** [eecrazy/ConstructingNEEG_IJCAI_2018#9]
In this py document, I found in the line 109:
u_c=torch.add(u_a2.view(5*len(hidden),8),u_b2.view(5*len(hidden),1))
This add operation has two different shapes ([5*len(hidden),8], [5*len(hidden),1]). How does this function work in this situation?

**Comment by eecrazy** [comment]
You can look up the PyTorch documents. It should expand the second Tensor as the first one's shape, then add.

**Comment by floatSDSDS** [comment]
> In this py document, I found in the line 109:
> u_c=torch.add(u_a2.view(5_len(hidden),8),u_b2.view(5_len(hidden),1))
> This add operation has two different shapes ([5_len(hidden),8], [5_len(hidden),1]). How does this function work in this situation?

Hi. I'm Lu, a collaborator of one of the repos you cloned. We have made some serious mistakes in the code and I need to fix it up. Specifically, we need you to delete the current fork and re-fork the latest version. So, is it possible for you to email me float.hellowmr@gmail.com for details? Sorry to bother you and thanks!

Lu
